project_name: dynamodb-backup-restore

release:
  github:
    owner: kishaningithub
    name: dynamodb-backup-restore

before:
  hooks:
  - go mod download

builds:
- main: ./main.go
  binary: dynamodb-backup-restore
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - 386
brew:
  name: dynamodb-backup-restore
  github:
    owner: kishaningithub
    name: homebrew-tap
  url_template: "https://github.com/kishaningithub/dynamodb-backup-restore/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  folder: Formula
  homepage: "https://github.com/kishaningithub/dynamodb-backup-restore"
  description: "A no sweat backup and restore tool for dynamodb"