sudo: false
language: go

env:
  global:
    - secure: "QPbIw2kVlR6tBsRuaQwm2FikKXUgA4REtDwW09AEDj1P9WMfFXMFmjcm00z0bDRCXg3pE5OT1a8G9ThP7gKXauPjBIDv01e5CndLmUHEcL7ENVBQgmCQKmfpVKW5gvnlRv0WecBuZ4avre+PHrBddtXpcgM8NDQFUFtOu+8tXYPJkcanwouyd2ayOW1EHWpNV0umvABOi5Ji6T7VFY/wuKWaSaglwfdYPRgpYOj8A/cANyBPC0xCV8Evr7a+ntnlPRkvC4W1v4LYd8a9cmSZD7SF5Yt7MX8X9nAUMqSJLz9T8hs7AQYDa/eQpccc9aLyndjqknNy+m5sZeMPlPyr2hrwzpuc0TTltSYnYj5q3BGso9jrZOt/+74SGNWfUcMOugOqjRwq5zRvGjvAYTvoNmewpAaVpAY8F0Ygk7NNQse7roJJQwf6nBOPniHAYxU4FmN5EiZD4sQa8HxLKjiWtZ9oXkpYgAiHi6ZRHJa+9H0vf8iZWor/MJEALDYd5ZV2vE7QNdjM5c8AE3skkye7ffuE336V2hpUXz9pizCwEJbsb+HOGYusHW3eTuAaHJ+tlYIa2oN8ZsOXqUd/ZjMHP4LWR0DIHFqrnnKI+Hxob9JnmW+5xUzbsf57pSlVLNJNS/JIKCCukO84DYirOt617QqJsU9qsqn3HFCgUYm+G1w="

go:
- 1.12.x
install:
- GO111MODULE=on go get -t -v ./...
script:
- GO111MODULE=on go test -v ./...
after_success:
- export GO111MODULE=on
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash